# Generated by Django 5.1.3 on 2024-11-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfidLog', '0002_alter_employee_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidlog',
            name='type',
            field=models.CharField(max_length=3),
        ),
    ]
