# Generated by Django 5.1.3 on 2024-11-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfidLog', '0003_alter_rfidlog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='icon',
            field=models.CharField(default='./templates/assets/person.jpg', max_length=100),
        ),
    ]
