# Generated by Django 5.1.3 on 2024-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfidLog', '0004_employee_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='icon',
            field=models.CharField(default='./assets/person.jpg', max_length=100),
        ),
    ]
