# Generated by Django 5.1.3 on 2024-11-22 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfidLog', '0005_alter_employee_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rfidlog',
            name='sensor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rfidLog.sensor'),
        ),
    ]
