# Generated by Django 5.1.3 on 2024-11-22 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfidLog', '0007_remove_rfidlog_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidlog',
            name='sensor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rfidLog.sensor'),
        ),
    ]
