# Generated by Django 5.1.3 on 2024-11-23 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfidLog', '0008_rfidlog_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
